FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

ARG HASHED_SECRET=secret
ARG USER_SERVER_URL=http://localhost:8080/user
ARG PRODUCT_SERVER_URL=http://localhost:8081/product
ARG AUTH_SERVER_URL=http://localhost:8082/auth
ARG CART_SERVER_URL=http://localhost:8083/cart
ARG LIKE_SERVER_URL=http://localhost:8084/like
ARG ORDER_SERVER_URL=http://localhost:8085/order
ARG JWT_SECRET=secret
ARG APPLICATION_PORT=3002

ENV HASHED_SECRET=HASHED_SECRET
ENV USER_SERVER_URL=USER_SERVER_URL
ENV PRODUCT_SERVER_URL=PRODUCT_SERVER_URL
ENV AUTH_SERVER_URL=AUTH_SERVER_URL
ENV CART_SERVER_URL=CART_SERVER_URL
ENV LIKE_SERVER_URL=LIKE_SERVER_URL
ENV ORDER_SERVER_URL=ORDER_SERVER_URL
ENV JWT_SECRET=JWT_SECRET
ENV APPLICATION_PORT=APPLICATION_PORT

RUN npm i
COPY . .

EXPOSE 3002
CMD [ "node", "src/index.js" ]
